{
    "openapi": "3.0.1",
    "info": {
        "title": "Marketing Events",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "cms": "STARTER"
        },
        "x-hubspot-documentation-banner": "PUBLIC_BETA",
        "x-hubspot-api-use-case": "You have an external system that handles registration for your webinars and you want to ensure that attendee data and behavior is synced with your HubSpot CRM.",
        "x-hubspot-related-documentation": [
            {
                "name": "Marketing Events Guide",
                "url": "https://developers.hubspot.com/beta-docs/guides/api/marketing/marketing-events"
            }
        ],
        "x-hubspot-introduction": "A marketing event is a CRM object, similar to contacts and companies, that enables you to track marketing events, such as a webinar, along with the contacts who registered and attended the event. Below, learn more about working with the marketing event API to integrate marketing events into an app."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/marketing/v3/marketing-events"
        }
    ],
    "tags": [
        {
            "name": "Add event attendees"
        },
        {
            "name": "Retrieve Participant State"
        },
        {
            "name": "Subscriber State Changes"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Batch"
        },
        {
            "name": "List Associations"
        },
        {
            "name": "Identifiers"
        },
        {
            "name": "Change property"
        },
        {
            "name": "Settings"
        }
    ],
    "paths": {
        "/attendance/{externalEventId}/{subscriberState}/create": {
            "post": {
                "tags": [
                    "Add event attendees"
                ],
                "summary": "Record participants by contact IDs",
                "description": "Records the participation of multiple HubSpot contacts in a Marketing Event using their HubSpot contact IDs.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
                "operationId": "post-/attendance/{externalEventId}/{subscriberState}/create_recordByContactIds",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/participations/{marketingEventId}/breakdown": {
            "get": {
                "tags": [
                    "Retrieve Participant State"
                ],
                "summary": "Get participations breakdown by event",
                "description": "Read Marketing event's participations breakdown with optional filters by internal identifier marketingEventId.",
                "operationId": "get-/participations/{marketingEventId}/breakdown_getParticipationsBreakdownByMarketingEventId",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            }
        },
        "/events/{externalEventId}/{subscriberState}/upsert": {
            "post": {
                "tags": [
                    "Subscriber State Changes"
                ],
                "summary": "Record subscriber state by contact",
                "description": "Record a subscriber state between multiple HubSpot contacts and a marketing event, using HubSpot contact IDs. Note that the contact must already exist in HubSpot; a contact will not be created.",
                "operationId": "post-/events/{externalEventId}/{subscriberState}/upsert_upsertByContactId",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/events/{externalEventId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Get Marketing Event by External IDs",
                "description": "Returns the details of a Marketing Event with the specified externalAccountId, externalEventId, if it exists.\n\nOnly Marketing Events created by the same app making the request can be retrieved.",
                "operationId": "get-/events/{externalEventId}_getDetails",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            },
            "put": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create or update a marketing event",
                "description": "Upserts a marketing event If there is an existing marketing event with the specified ID, it will be updated; otherwise a new event will be created.",
                "operationId": "put-/events/{externalEventId}_upsert",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Delete event by external IDs",
                "description": "Deletes the existing Marketing Event with the specified externalAccountId, externalEventId, if it exists.\n\nOnly Marketing Events created by the same app can be deleted.",
                "operationId": "delete-/events/{externalEventId}_archive",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update event by external IDs",
                "description": "Updates the details of an existing Marketing Event identified by its externalAccountId, externalEventId if it exists.\n\nOnly Marketing Events created by the same app can be updated.",
                "operationId": "patch-/events/{externalEventId}_update",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/events/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Upsert multiple marketing events",
                "description": "Upserts multiple Marketing Events. If a Marketing Event with the specified ID already exists, it will be updated; otherwise, a new event will be created.\n\nOnly Marketing Events originally created by the same app can be updated.",
                "operationId": "post-/events/upsert_batchUpsert",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/attendance/{externalEventId}/{subscriberState}/email-create": {
            "post": {
                "tags": [
                    "Add event attendees"
                ],
                "summary": "Record participants by email",
                "description": "Records the participation of multiple HubSpot contacts in a Marketing Event using their email addresses.\n\nIf a contact does not exist, it will be automatically created. The contactProperties field is used exclusively for creating new contacts and will not update properties of existing contacts.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
                "operationId": "post-/attendance/{externalEventId}/{subscriberState}/email-create_recordByContactEmails",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/participations/{externalAccountId}/{externalEventId}/breakdown": {
            "get": {
                "tags": [
                    "Retrieve Participant State"
                ],
                "summary": "Get participation breakdown",
                "description": "Read Marketing event's participations breakdown with optional filters by externalAccountId and externalEventId pair.",
                "operationId": "get-/participations/{externalAccountId}/{externalEventId}/breakdown_getParticipationsBreakdownByExternalEventId",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            }
        },
        "/{objectId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Get Marketing Event by objectId",
                "description": "Returns the details of a Marketing Event with the specified objectId, if it exists.",
                "operationId": "get-/{objectId}",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Delete Marketing Event by objectId",
                "description": "Deletes the existing Marketing Event with the specified objectId, if it exists.",
                "operationId": "delete-/{objectId}",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update Marketing Event by objectId",
                "description": "Updates the details of an existing Marketing Event identified by its objectId, if it exists.",
                "operationId": "patch-/{objectId}",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/associations/{externalAccountId}/{externalEventId}/lists": {
            "get": {
                "tags": [
                    "List Associations"
                ],
                "summary": "Get event-associated lists",
                "description": "Gets lists associated with a marketing event by external account id and external event id",
                "operationId": "get-/associations/{externalAccountId}/{externalEventId}/lists_getAllByExternalAccountAndEventIds",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/associations/{marketingEventId}/lists": {
            "get": {
                "tags": [
                    "List Associations"
                ],
                "summary": "Get event-associated lists",
                "description": "Gets lists associated with a marketing event by marketing event id",
                "operationId": "get-/associations/{marketingEventId}/lists_getAllByMarketingEventId",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/{objectId}/attendance/{subscriberState}/email-create": {
            "post": {
                "tags": [
                    "Add event attendees"
                ],
                "summary": "Record participants by email",
                "description": "Records the participation of multiple HubSpot contacts in a Marketing Event using their email addresses.\n\nIf a contact does not exist, it will be automatically created. The contactProperties field is used exclusively for creating new contacts and will not update properties of existing contacts.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
                "operationId": "post-/{objectId}/attendance/{subscriberState}/email-create",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Get all marketing event",
                "description": "Returns all Marketing Events available on the portal, along with their properties, regardless of whether they were created manually or through the application.\n\nThe marketing events returned by this endpoint are sorted by objectId.",
                "operationId": "get-/",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            }
        },
        "/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Batch update events by ObjectId",
                "description": "Updates multiple Marketing Events on the portal based on their objectId, if they exist.",
                "operationId": "post-/batch/update",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/{objectId}/attendance/{subscriberState}/create": {
            "post": {
                "tags": [
                    "Add event attendees"
                ],
                "summary": "Record participants by contact ID",
                "description": "Records the participation of multiple HubSpot contacts in a Marketing Event using their HubSpot contact IDs.\n\nAdditional Functionality:\n- Adds a timeline event to the contacts.\n\nAllowed Properties:\nFor the state \"attend\":\n- joinedAt\n- leftAt",
                "operationId": "post-/{objectId}/attendance/{subscriberState}/create",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Batch delete events by ObjectId",
                "description": "Deletes multiple Marketing Events from the portal based on their objectId, if they exist.\n\nResponses:\n204: Returned if all specified Marketing Events were successfully deleted.\n207: Returned if some objectIds did not correspond to any existing Marketing Events.",
                "operationId": "post-/batch/archive",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/participations/{externalAccountId}/{externalEventId}": {
            "get": {
                "tags": [
                    "Retrieve Participant State"
                ],
                "summary": "Get participation counters",
                "description": "Read Marketing event's participations counters by externalAccountId and externalEventId pair.",
                "operationId": "get-/participations/{externalAccountId}/{externalEventId}_getParticipationsCountersByEventExternalId",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            }
        },
        "/{externalEventId}/identifiers": {
            "get": {
                "tags": [
                    "Identifiers"
                ],
                "summary": "Find events by externalEventId",
                "description": "This endpoint searches the portal for all Marketing Events whose externalEventId matches the value provided in the request.\n\nIt retrieves the objectId and additional event details for each matching Marketing Event.\n\nSince multiple Marketing Events can have the same externalEventId, the endpoint returns all matching results.\n\nNote: Marketing Events become searchable by externalEventId a few minutes after creation.",
                "operationId": "get-/{externalEventId}/identifiers",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            }
        },
        "/participations/{marketingEventId}": {
            "get": {
                "tags": [
                    "Retrieve Participant State"
                ],
                "summary": "Get participation counters",
                "description": "Read Marketing event's participations counters by internal identifier marketingEventId.",
                "operationId": "get-/participations/{marketingEventId}_getParticipationsCountersByMarketingEventId",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            }
        },
        "/events/delete": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Batch delete by external IDs",
                "description": "Deletes multiple Marketing Events based on externalAccountId, externalEventId, and appId.\n\nOnly Marketing Events created by the same apps will be deleted; events from other apps cannot be removed by this endpoint. ",
                "operationId": "post-/events/delete_batchArchive",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/events/{externalEventId}/cancel": {
            "post": {
                "tags": [
                    "Change property"
                ],
                "summary": "Mark a marketing event as cancelled",
                "description": "Mark a marketing event as cancelled.",
                "operationId": "post-/events/{externalEventId}/cancel_cancel",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/associations/{marketingEventId}/lists/{listId}": {
            "put": {
                "tags": [
                    "List Associations"
                ],
                "summary": "Associate list with event",
                "description": "Associates a list with a marketing event by marketing event id and ILS list id",
                "operationId": "put-/associations/{marketingEventId}/lists/{listId}_associateByMarketingEventId",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "List Associations"
                ],
                "summary": "Disassociate list from event",
                "description": "Disassociates a list from a marketing event by marketing event id and ILS list id",
                "operationId": "delete-/associations/{marketingEventId}/lists/{listId}_disassociateByMarketingEventId",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/events/{externalEventId}/{subscriberState}/email-upsert": {
            "post": {
                "tags": [
                    "Subscriber State Changes"
                ],
                "summary": "Record subscriber state by email",
                "description": "Record a subscriber state between multiple HubSpot contacts and a marketing event, using contact email addresses. Note that the contact must already exist in HubSpot; a contact will not be created. The contactProperties field is used only when creating a new contact. These properties will not update existing contacts. ",
                "operationId": "post-/events/{externalEventId}/{subscriberState}/email-upsert_upsertByContactEmail",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/associations/{externalAccountId}/{externalEventId}/lists/{listId}": {
            "put": {
                "tags": [
                    "List Associations"
                ],
                "summary": "Associate list with event",
                "description": "Associates a list with a marketing event by external account id, external event id, and ILS list id",
                "operationId": "put-/associations/{externalAccountId}/{externalEventId}/lists/{listId}_associateByExternalAccountAndEventIds",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "List Associations"
                ],
                "summary": "Disassociate a list from event",
                "description": "Disassociates a list from a marketing event by external account id, external event id, and ILS list id",
                "operationId": "delete-/associations/{externalAccountId}/{externalEventId}/lists/{listId}_disassociateByExternalAccountAndEventIds",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/events/{externalEventId}/complete": {
            "post": {
                "tags": [
                    "Change property"
                ],
                "summary": "Mark a marketing event as completed",
                "description": "Mark a marketing event as completed",
                "operationId": "post-/events/{externalEventId}/complete_complete",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/events": {
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a marketing event",
                "description": "Creates a new marketing event in HubSpot",
                "operationId": "post-/events_create",
                "security": [
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    }
                ]
            }
        },
        "/participations/contacts/{contactIdentifier}/breakdown": {
            "get": {
                "tags": [
                    "Retrieve Participant State"
                ],
                "summary": "Get participation breakdown",
                "description": "Read Contact's participations by identifier - email or internal id.",
                "operationId": "get-/participations/contacts/{contactIdentifier}/breakdown_getParticipationsBreakdownByContactId",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            }
        },
        "/{appId}/settings": {
            "get": {
                "tags": [
                    "Settings"
                ],
                "summary": "Retrieve the application settings",
                "description": "Retrieve the current settings for the application.",
                "operationId": "get-/{appId}/settings_getAll",
                "security": [
                    {
                        "developer_hapikey": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Settings"
                ],
                "summary": "Update the application settings",
                "description": "Create or update the current settings for the application.",
                "operationId": "post-/{appId}/settings_update",
                "security": [
                    {
                        "developer_hapikey": []
                    }
                ]
            }
        },
        "/events/search": {
            "get": {
                "tags": [
                    "Identifiers"
                ],
                "summary": "Find events by external ID",
                "description": "Retrieves Marketing Events where the externalEventId matches the value provided in the request, limited to events created by the app making the request.\n\nMarketing Events created by other apps will not be included in the results.",
                "operationId": "get-/events/search_doSearch",
                "security": [
                    {
                        "oauth2_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.marketing_events.read": "Read marketing events",
                            "crm.objects.marketing_events.write": "Write marketing events"
                        }
                    }
                }
            },
            "developer_hapikey": {
                "type": "apiKey",
                "name": "hapikey",
                "in": "query"
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "cms": "STARTER"
    },
    "x-hubspot-documentation-banner": "PUBLIC_BETA"
}